name = "MirroredArrayViews"
uuid = "edfed022-ddf0-11e8-3461-e736d26fdb96"
authors = ["Sean McBane <sean@ices.utexas.edu>"]
version = "1.0.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
